name: Upload Python Package

on:
  push:
    branches: [ master ]

jobs:
  deploy-bdist-windows:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        os: ['windows-latest']
        architecture: ['x64']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install-deps
      run: |
        "%VS140COMNTOOLS%../../VC/vcvarsall.bat"
        reg.exe query "HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0" /v MSBuildToolsPath
        # "%VS140COMNTOOLS%../../VC/vcvarsall.bat"
        svn co svn://vcs.exim.org/pcre/code/trunk pcre
        cd pcre
        cmake.exe .
        C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe PCRE.sln
        dir D:/a/pyautocorpus/pyautocorpus/pcre
        cd ..
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: build
      run: |
        "%VS140COMNTOOLS%../../VC/vcvarsall.bat"
        echo "D:\a\pyautocorpus\pyautocorpus\pcre" >> $PCRE_HOME 
        python setup.py bdist_wheel
    - uses: actions/upload-artifact@v2
      with:
        name: bdist-windows
        path: dist/*
    # - name: upload
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: |
    #     twine upload dist/*
