name: Test Action

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true

jobs:
  deploy-bdist-manylinux2014:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install-deps
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.0.0
      with:
        output-dir: wheelhouse
      env:
        CIBW_BEFORE_ALL: "yum install -y pcre pcre-devel"
    # - name: upload
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: |
    #     twine upload wheelhouse/*
    - uses: actions/upload-artifact@v2
      with:
        name: bdist-manylinux2014
        path: wheelhouse/*
